### PR TITLE
Show remaining balance and add button for adding funds

### PR DESCRIPTION
**Pull request by jstarry**
Related to https://github.com/solana-labs/solana/issues/4858
Depends on https://github.com/solana-labs/example-webwallet/pull/240

Changes:
* Some UI updates
* To use the dApp, users must now first fund their account from a wallet
---
Current payer account balance
Screenshot 2019-07-11 10 11 19

Add funds call to action
Screenshot 2019-07-11 10 03 23

### CODE REVIEW

**Comment by jstarry** [comment]
Wallet url construction is a bit janky, I think it might be better to set a config var in heroku

**Comment by jstarry** [comment]
@mvines I'm starting to feel like I took the wrong approach here. Was the goal to fund the drone account or a separate user account interacting with the dApp?

Right now, as I understand it, the message feed dApp only interacts with a drone to fetch information about the program and then request that a user account is created (login). After that, it funds and signs transactions client-side to post messages or ban other users.

I imagine that it is desirable to have some way for a dApp owner to fund their drone service but can also imagine users want to fund their accounts so that they can post messages.

**Comment by mvines** [comment]
> Wallet url construction is a bit janky, I think it might be better to set a config var in heroku

Heh, yeah I agree.   It could come in from the server via https://github.com/solana-labs/example-messagefeed/blob/ee4291516ea194835e119d762ef1d056d9d9a08e/src/server.js#L109-L126

**Comment by mvines** [comment]
> @mvines I'm starting to feel like I took the wrong approach here. Was the goal to fund the drone account or a separate user account interacting with the dApp?

This: "separate user account interacting with the dApp?"

But the server also uses the drone to fund loading of the program, I think that's ok to retain as is for now.  Presumably the dApp owner already has access to a font of tokens.

**Comment by jstarry** [comment]
@mvines can you take another look? Switched to using window messages to interact with the web wallet and added an env var for the wallet url

**Pull request merged**
